import React from 'react';
import { Container, Accordion, Card, Row, Col } from 'react-bootstrap';
import { HelpCircle, Mail, MessageSquare } from 'lucide-react';
import { Link } from 'react-router-dom';
import PublicNavbar from '../components/PublicNavbar';
import ParticleCanvas from '../components/ParticleCanvas';

const Help = () => {
    return (
        <div className="bg-body-tertiary min-vh-100 font-sans position-relative overflow-hidden">
            <div className="position-fixed w-100 h-100 top-0 start-0" style={{ zIndex: 0, pointerEvents: 'none' }}>
                <ParticleCanvas />
            </div>
            <div className="position-absolute top-0 start-50 translate-middle-x w-100 h-100" style={{
                background: 'radial-gradient(circle at 50% 0%, rgba(13,110,253,0.08) 0%, transparent 50%), radial-gradient(circle at 80% 20%, rgba(13,202,240,0.05) 0%, transparent 40%)',
                zIndex: 0, pointerEvents: 'none'
            }}></div>
            <PublicNavbar />
            <Container className="position-relative z-1" style={{ paddingTop: '140px', paddingBottom: '60px' }}>
                <div className="text-center mb-5 pb-3">
                    <HelpCircle size={48} className="text-primary mb-3" />
                    <h1 className="fw-bolder display-5 text-body tracking-tight">How can we help you?</h1>
                    <p className="lead text-muted mx-auto" style={{ maxWidth: '600px' }}>
                        Browse our frequently asked questions, or reach out to our dedicated support team.
                    </p>
                </div>

                <Row className="g-4 mb-5">
                    <Col lg={8} className="mx-auto">
                        <Card className="border-0 shadow-sm rounded-4 overflow-hidden mb-5">
                            <Card.Body className="p-0">
                                <Accordion flush>
                                    <Accordion.Item eventKey="0">
                                        <Accordion.Header className="fw-bold">How do I reset my password?</Accordion.Header>
                                        <Accordion.Body className="text-muted">
                                            If you've forgotten your password, click the "Forgot Password" link on the login screen. You will receive an email containing a secure link to create a new password.
                                        </Accordion.Body>
                                    </Accordion.Item>
                                    <Accordion.Item eventKey="1">
                                        <Accordion.Header className="fw-bold">Are the certificates recognized globally?</Accordion.Header>
                                        <Accordion.Body className="text-muted">
                                            Yes! Every certificate generated by the Dawn platform includes a cryptographic QR code that allows employers to instantly verify your credentials on our blockchain-backed registry.
                                        </Accordion.Body>
                                    </Accordion.Item>
                                    <Accordion.Item eventKey="2">
                                        <Accordion.Header className="fw-bold">Can I switch my account from Student to Teacher?</Accordion.Header>
                                        <Accordion.Body className="text-muted">
                                            Account roles are permanently assigned upon registration to maintain database integrity. If you wish to become an instructor, please create a new teacher account or contact support.
                                        </Accordion.Body>
                                    </Accordion.Item>
                                    <Accordion.Item eventKey="3">
                                        <Accordion.Header className="fw-bold">Do I need to pay for courses upfront?</Accordion.Header>
                                        <Accordion.Body className="text-muted">
                                            Pricing is determined by individual instructors. Some courses are entirely free, while others require a one-time payment using integrated wallets like eSewa or Khalti.
                                        </Accordion.Body>
                                    </Accordion.Item>
                                </Accordion>
                            </Card.Body>
                        </Card>

                        <Row className="g-4 text-center">
                            <Col md={6}>
                                <Card className="border-0 shadow-sm rounded-4 h-100">
                                    <Card.Body className="p-4">
                                        <div className="bg-primary bg-opacity-10 d-inline-block p-3 rounded-circle mb-3"><Mail className="text-primary" size={24}/></div>
                                        <h5 className="fw-bold">Email Support</h5>
                                        <p className="text-muted small">support@dawnplatform.com</p>
                                    </Card.Body>
                                </Card>
                            </Col>
                            <Col md={6}>
                                <Card className="border-0 shadow-sm rounded-4 h-100">
                                    <Card.Body className="p-4">
                                        <div className="bg-success bg-opacity-10 d-inline-block p-3 rounded-circle mb-3"><MessageSquare className="text-success" size={24}/></div>
                                        <h5 className="fw-bold">Live Chat</h5>
                                        <p className="text-muted small">Available 24/7 for Pro Users</p>
                                    </Card.Body>
                                </Card>
                            </Col>
                        </Row>
                    </Col>
                </Row>
            </Container>
        </div>
    );
};

export default Help;
